### ISSUE TITLE
$producerTopic delete dumps core

### ISSUE THREAD

**Issue by mutability** [flightaware/kafkatcl#17]
kafkatcl 2.1.0 with librdkafka 0.9.5

```
07/18/2017 12:00:44 shutting down kafka (queue size 53912)
07/18/2017 12:00:44 waiting for kafka output queue to empty (53912)
07/18/2017 12:00:45 waiting for kafka output queue to empty (21973)
delete hexid topic
delete facility topic
Bus error (core dumped)
```

```
(gdb) bt
#0  0x0000000804a50cb4 in kafkatcl_topicObjectDelete () from /usr/local/lib/kafka2.1/libkafka.so.1
#1  0x0000000800863b7a in Tcl_DeleteCommandFromToken () from /usr/local/lib/libtcl86.so.1
#2  0x0000000804a4fe82 in kafkatcl_topicProducerObjectObjCmd () from /usr/local/lib/kafka2.1/libkafka.so.1
```

This is a setup where there are two producers created via ::kafka::topic_producer;
some messages are produced;
then I wait for the output queue length to reach zero;
then the two topics are deleted

The first one deletes OK, the second delete dumps core.

**Comment by resuna** [comment]
Fixed in f533bc0a1556e1337c1290425a646da3673dce41
